### ISSUE TITLE
Seems some rpm dependency fields should be optional

### ISSUE THREAD

**Issue by dparalen** [dparalen/pulp_solv#3]
Just ran into this stacktrace:

```
processing unit {u'release': None, u'epoch': None, u'version': None, u'flags': None, u'name': u'wolf'} attribute flags value None
Traceback (most recent call last):
  File "pulpsolv.py", line 358, in <module>
    load_repo_units(pm, args.source_repo, source_unit_solvable_factory_mapping)
  File "pulpsolv.py", line 327, in load_repo_units
    factory(unit)
  File "pulpsolv.py", line 260, in __call__
    attribute_factory(solvable, unit, self)
  File "pulpsolv.py", line 219, in __call__
    dependency_unit_infos = getattr(unit, self.attr_name)
AttributeError: 'RPM' object has no attribute 'conflicts'
```
Seems like the `RpmDependencyAttributeFactory` might benefit inheriting from the `AttributeFactory`,
to avoid having to duplicate  the handling of an optional attribute.
Previously I did have a generic compound attribute factory:

```python
class CompoundAttributeFactory(AttributeFactory):

    attribute_factories = []

    class Adaptor:
        pass

    def compound(self, adaptor):
        # by default, just join the attributes
        return " ".join([str(getattr(adaptor, attribute_factory.attr_name))
                                  for attribute_factory in self.attribute_factories])

    def __call__(self, solvable, unit, solvable_factory):
        # process the compound attributes with a fake solvable
        adaptor = self.Adaptor()
        for attribute_factory in self.attribute_factories:
            attribute_factory(adaptor, unit, solvable_factory)

       # pretend to be the unit, the source of the compound
       # attribute value
       setattr(self, self.attr_name, self.compound(adaptor))
       return super(self, CompoundAttributeFactory).__call__(
           solvable, self, solvable_factory)
```

Which worked but I thought it wasn't worth the complication.
Now I'm considering bringing it back in some form.

**Comment by dparalen** [comment]
Actually found a trivial fix for this \o/
